<?php
	if ($this->CheckLogin("read") && $this->CheckConfig()) {
		// first do normal copyto
		if (!($result=$this->call("pobject::system.copyto.phtml", $arCallArgs))) {
			if ($newpath=$ARCurrent->newpath && $newid=$ARCurrent->newid) {
				// no errors: copy files
				$files=$this->store->get_filestore("files");
				$files->copy($this->id, null, $ARCurrent->newid, null);
			}
		} else {
			$arResult=$result;
		}
	}
?>
